#!/usr/bin/env python3
"""
Interactive setup script for email and SMS verification
This script will guide you through setting up Gmail and Twilio
"""

import os
import sys
from pathlib import Path

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def print_step(num, text):
    """Print a step"""
    print(f"\n📋 Step {num}: {text}")
    print("-" * 60)

def create_env_file():
    """Create .env file interactively"""
    env_path = Path('.env')
    
    if env_path.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("Keeping existing .env file.")
            return False
    
    print_header("Email & SMS Verification Setup")
    print("This script will help you configure Gmail SMTP and Twilio SMS.")
    print("You'll need:")
    print("  • Gmail account with 2FA enabled")
    print("  • Gmail App Password")
    print("  • Twilio account (free trial available)")
    print("  • Twilio Account SID, Auth Token, and Phone Number")
    
    input("\nPress Enter to continue...")
    
    # Email Configuration
    print_step(1, "Gmail SMTP Configuration")
    print("\n📧 Setting up email verification...")
    print("\nFirst, you need to:")
    print("  1. Enable 2FA on Gmail: https://myaccount.google.com/security")
    print("  2. Create App Password: https://myaccount.google.com/apppasswords")
    print("     - Select 'Mail' → 'Other' → Name it 'Family Hub'")
    print("     - Copy the 16-character password")
    
    input("\nPress Enter when you have your Gmail App Password ready...")
    
    smtp_user = input("\nEnter your Gmail address: ").strip()
    smtp_password = input("Enter your Gmail App Password (16 characters, no spaces): ").strip().replace(' ', '')
    
    if not smtp_user or not smtp_password:
        print("❌ Email configuration incomplete. Skipping...")
        smtp_user = ""
        smtp_password = ""
    
    # SMS Configuration
    print_step(2, "Twilio SMS Configuration")
    print("\n📱 Setting up SMS verification...")
    print("\nFirst, you need to:")
    print("  1. Sign up for Twilio: https://www.twilio.com/try-twilio")
    print("  2. Get credentials from: https://console.twilio.com")
    print("     - Account SID (starts with AC)")
    print("     - Auth Token")
    print("     - Phone Number (use trial number for testing)")
    
    response = input("\nDo you have Twilio credentials ready? (y/n): ").strip().lower()
    
    twilio_sid = ""
    twilio_token = ""
    twilio_phone = ""
    
    if response == 'y':
        twilio_sid = input("\nEnter Twilio Account SID: ").strip()
        twilio_token = input("Enter Twilio Auth Token: ").strip()
        twilio_phone = input("Enter Twilio Phone Number (format: +1234567890): ").strip()
        
        if not twilio_sid or not twilio_token or not twilio_phone:
            print("⚠️  Twilio configuration incomplete. You can add it later.")
            twilio_sid = ""
            twilio_token = ""
            twilio_phone = ""
    else:
        print("⚠️  Skipping Twilio setup. You can add it later in .env file.")
    
    # Create .env file
    print_step(3, "Creating .env File")
    
    env_content = f"""# Backend Environment Variables
# Generated by setup_verification.py

# ==================== EMAIL CONFIGURATION ====================
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER={smtp_user}
SMTP_PASSWORD={smtp_password}
EMAIL_FROM=noreply@family-housing-hub.com

# ==================== SMS CONFIGURATION ====================
TWILIO_ACCOUNT_SID={twilio_sid}
TWILIO_AUTH_TOKEN={twilio_token}
TWILIO_PHONE_NUMBER={twilio_phone}

# ==================== FLASK CONFIGURATION ====================
FLASK_ENV=development
PORT=5000
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("✅ .env file created successfully!")
        return True
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def test_configuration():
    """Test the configuration"""
    print_step(4, "Testing Configuration")
    
    from dotenv import load_dotenv
    load_dotenv()
    
    smtp_user = os.getenv('SMTP_USER')
    smtp_password = os.getenv('SMTP_PASSWORD')
    twilio_sid = os.getenv('TWILIO_ACCOUNT_SID')
    twilio_token = os.getenv('TWILIO_AUTH_TOKEN')
    twilio_phone = os.getenv('TWILIO_PHONE_NUMBER')
    
    print("\n📋 Configuration Summary:")
    print(f"  Email: {'✅ Configured' if smtp_user and smtp_password else '❌ Not configured'}")
    print(f"  SMS: {'✅ Configured' if twilio_sid and twilio_token and twilio_phone else '❌ Not configured'}")
    
    if not smtp_user and not twilio_sid:
        print("\n⚠️  No services configured. Please run this script again or edit .env manually.")
        return False
    
    response = input("\nWould you like to run the full test? (y/n): ").strip().lower()
    if response == 'y':
        print("\nRunning test_verification.py...")
        os.system('python test_verification.py')
    
    return True

def main():
    """Main setup function"""
    # Change to backend directory
    backend_dir = Path(__file__).parent
    os.chdir(backend_dir)
    
    print_header("Family Housing Hub - Verification Setup")
    
    # Check if we're in the right directory
    if not Path('app.py').exists():
        print("❌ Error: app.py not found. Please run this script from the backend/ directory.")
        sys.exit(1)
    
    # Create .env file
    if create_env_file():
        print("\n✅ Setup complete!")
        
        # Ask to test
        response = input("\nWould you like to test the configuration now? (y/n): ").strip().lower()
        if response == 'y':
            test_configuration()
        
        print("\n" + "="*60)
        print("🎉 Setup Complete!")
        print("="*60)
        print("\nNext steps:")
        print("  1. Install dependencies: pip install -r requirements.txt")
        print("  2. Test configuration: python test_verification.py")
        print("  3. Start backend: python app.py")
        print("  4. Test in your app!")
    else:
        print("\n⚠️  Setup incomplete. You can manually edit .env file or run this script again.")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)

